# Generated by Django 4.1.3 on 2022-12-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customuser_can_edit_customuser_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('dep_location', models.CharField(max_length=200)),
                ('arr_location', models.CharField(max_length=200)),
                ('ticket_info', models.CharField(max_length=2000)),
                ('vehicle_info', models.CharField(max_length=2000)),
                ('room_info', models.CharField(max_length=2000)),
                ('link', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=5000)),
                ('plantype_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.plantype')),
                ('trip_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.trip')),
            ],
        ),
    ]
